name: srt_parser
version: 1.1.0+2
description: A cross-platform, .srt parser that allows you to read a String containing Html and Coordinates and results to subtitle objects.

authors: 
  - Adrian Stabiszewski <as@grundid.de>
  - Arman Torkzaban <at@vo.tc>
homepage: https://git.mant.life/arman/srt_parser
repository: https://git.mant.life/arman/srt_parser
issue_tracker: https://git.mant.life/arman/srt_parser/issues

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  csslib: ^0.14.6
  meta: ^1.1.6

dev_dependencies:
  test: ^1.6.1
  
